# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "KrrXDgpxcFRo5qdHSoPNQg+62KF6h3PH+pHsqnDLVGmVc4bMO0luW38ahWt2mYZvEnQGQGLW9nHAD2DMfnrlhWf5GARUxBEKP1rZ//MToS6wyg+RfRzzrV2aSB0u79U8jqkGa3nqIZkQs+l6V2URqnBq+ztl09xfEx7598ovhu1O3txmqWkEYfmAxK3xWUyGV7MowmR49jpZBW1wOkrHwnRlxnrUKRB0TZVXbFREuT5aCm2Cu5sZvcflVij9SyG6iTh0X3NcP/xwEnlWz8wE755cbZbyv/IpGjJG84248D/1NhtdHR3pe7HiVc9ZTyHJhKlEMqG/Wz6namLgjBXWqglm28wVN54OrnbGxBGGfai8LBXDpT5euPQUMLyMCPNuDGyPpHeVmBXPcQS8K9odu3Les3XUQTr2HlMNWUQSCH8A2BF0f8dq9Xe4wiE20kQUCdqUA6WAvuNqDb7SdwIyYlVZoSNns0fJgXVX28lj++syJ/kV3ALSpYioJ2dMiJemh+GocwiLmRbwe+ExOumHgU3Zk2vihDebklsbJiIjMqodeYXOAtk8iaujT8Bu+0r11Fy5iPYbDg/US/PTsac2/xjPRlGhol+c2PgCYbS8DkUiy2UMfZOI91J844T2BX/GNU5YQDwJ9jT0WRnGMseOXwHaBt7ZS8BXKrhprkN7nns="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
