travis:
  secure:
    BINSTAR_TOKEN: hCpbGG+YcGNavP5z/rDSflCQHX0ww2PYvJMiD1n2X1NXTM5PCjt1AKgzCiwTBHwTrXGhmVPbYKudbiRlCGFaJxlE51YFgKMdEXr1n7B4/m3FhX4jKEfltRiodVCestiePcJL+T5wamb4JQDNCwbMEzypdi6FyDjnMn/R+tIRdCl4j4bVLyaoMfHCwkHWfwzcpi4jrHC6miTExyIyxo2MdFlG+cqB3/J0A+mFpldKm2SI5ozWLqEP7+Os6DFqscCzZFv9TMNccpa3fL1AeDe8dslv+vbxRJ0e2DsjUYMa+u4pi6UFMJRMNA01w7fQC0lsuZUTXF5BxPqJsrfeaQ4Gj8XtQ3/NfFgaBBt0QDiq8BvVuyObDF4tCKOnh3pianSgHsdhPRz3EUNl1mWcnJjYwnNXD+wiYVyeIXthoAM8JLoHnxLjMZEZBdwVB/0lwnhvgY3pwAN8jtEwCW0wizBnEK0+1ktBoqCRc+qhQBM474J6Fg/vgeSC3b0xZkoHZ/X5dgD2ggWo0T86sqJugV9XOfg4d5wxjYIP65cMV2/T1wOH/9zcQY+ChQe7YOhkDGeM87IH7CvgKlgAvGdz1Uz8SAQSX+tW0+CmaywlVqVOLUvKF+rXkffQ7QmTF4Anyq0g42ileRVDxaxmEMAMHwhAXEcxH33DiJJxEjFUy4D+sMM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
