appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: KrrXDgpxcFRo5qdHSoPNQg+62KF6h3PH+pHsqnDLVGmVc4bMO0luW38ahWt2mYZvEnQGQGLW9nHAD2DMfnrlhWf5GARUxBEKP1rZ//MToS6wyg+RfRzzrV2aSB0u79U8jqkGa3nqIZkQs+l6V2URqnBq+ztl09xfEx7598ovhu1O3txmqWkEYfmAxK3xWUyGV7MowmR49jpZBW1wOkrHwnRlxnrUKRB0TZVXbFREuT5aCm2Cu5sZvcflVij9SyG6iTh0X3NcP/xwEnlWz8wE755cbZbyv/IpGjJG84248D/1NhtdHR3pe7HiVc9ZTyHJhKlEMqG/Wz6namLgjBXWqglm28wVN54OrnbGxBGGfai8LBXDpT5euPQUMLyMCPNuDGyPpHeVmBXPcQS8K9odu3Les3XUQTr2HlMNWUQSCH8A2BF0f8dq9Xe4wiE20kQUCdqUA6WAvuNqDb7SdwIyYlVZoSNns0fJgXVX28lj++syJ/kV3ALSpYioJ2dMiJemh+GocwiLmRbwe+ExOumHgU3Zk2vihDebklsbJiIjMqodeYXOAtk8iaujT8Bu+0r11Fy5iPYbDg/US/PTsac2/xjPRlGhol+c2PgCYbS8DkUiy2UMfZOI91J844T2BX/GNU5YQDwJ9jT0WRnGMseOXwHaBt7ZS8BXKrhprkN7nns=
